from server.representations.character_representation import (
    build_character_representation,
)
from server.representations.plot_representation import build_plot_representation
from server.representations.scene_representation import build_scene_representation
from server.representations.utils import graph_path_for